hostname: drifter

appVersions:
  node: node_14.x

aptKeys:
  # NodeJs
  - id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /usr/share/keyrings/nodesource-archive-keyring.gpg
  # Docker
  - id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

aptRepos:
  - file: nodesource
    repo: deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/{{ appVersions.node }} {{ ansible_lsb.codename }} main
  - file: nodesource
    repo: deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/{{ appVersions.node }} {{ ansible_lsb.codename }} main
  - file: docker
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

aptPackages:
  - docker-ce
  - gnome-shell-extension-appindicator
  - jq
  - nodejs
  - snapd
  - steam
  - tilix
  - zsh

  # - enpass
  # - gimp
  # - vim
  # - google-chrome-stable
  # - python3-pip
  # - nautilus-image-converter
