hostname: drifter

appVersions:
  node: node_14.x

aptKeys:
  # NodeJs
  - id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /usr/share/keyrings/nodesource-archive-keyring.gpg
  # Docker
  - id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  - id: 2012EA22
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
  # Proton does not currently sign their deb package so this throws an error
  # - id: 19940E11
  #   url: https://repo.protonvpn.com/debian/public_key.asc
  #   keyring: /usr/share/keyrings/protonvpn-archive-keyring.gpg

aptRepos:
  - file: nodesource
    repo: deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/{{ appVersions.node }} {{ ansible_lsb.codename }} main
  - file: nodesource
    repo: deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/{{ appVersions.node }} {{ ansible_lsb.codename }} main
  - file: docker
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  # See above section in aptKeys
  # - file: protonvpn
  #   repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://repo.protonvpn.com/debian/ stable main
  - file: git
    repo: ppa:git-core/ppa
  - file: 1password
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main

aptPackages:
  - docker-ce
  - gnome-shell-extension-appindicator
  - jq
  - nodejs
  - snapd
  - steam
  - tilix
  - zsh
  - git
  - 1password
  - neofetch
  - python3-pip
  #- dotnet-sdk-6.0

snapPackages:
  - slack
  - kubectl
  - helm
  - code

# future use maybe
# flatPaks:
#   -